spring:
  config:
    activate:
      on-profile: dev


info:
  datasource:
    url: jdbc:h2:mem:devdb
    driver-class-name: org.h2.Driver
    username: discodeit_user
    password: discodeit1234
  jpa:
    ddl-auto: update
  storage:
    type: file
    path: /dev/storage
  multipart:
    max-file-size: 10MB
    mac-request-size: 50MB

logging:
  level:
    root: info
    com.sprint.mission.discodeit : debug
    org.hibernate.SQL : debug