discodeit:
  storage:
    type: local
    local:
      root-path: .discodeit/storage

spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 100
  profiles:
    active: local
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB  # 업로드할 파일 최대 크기
      max-request-size: 10MB


  datasource:
    url: jdbc:postgresql://localhost:5432/discodeit
    username: discodeit_user
    password: discodeit1234
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10


logging:
  level:
    root:
    org.springframework.web: DEBUG
    org.springframework.web.servlet: DEBUG
    org.hibernate.sql: debug
    org.hibernate.orm.jdbc.bind: trace

