spring:
  application:
    name: discodeit
  servlet:
    multipart:
      enabled: true
      maxFileSize: 100MB # 파일 하나의 최대 크기
      maxRequestSize: 500MB  # 한 번에 최대 업로드 가능 용량
  datasource:
    url: jdbc:postgresql://localhost:5432/discodeit
    username: discodeit_user
    password: discodeit1234
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  sql:
    init:
      mode: always
server:
  port: 8080

discodeit:
  storage:
    local:
      root-path: /tmp/discodeit-storage
